Noodling around
netamorphosis/teastack-starter pull request #2
Opened 2021-09-10 23:10 UTC by netamorphosis-dev

Added new post type for Social Accounts -- got it working except for the correct icon field in the preview pane! This is cool af.

2021-09-10 23:36 UTC, franknoirot requested changes
Little edit, that icon picker is powered by a plugin that has its own little `preview()` utility function.

2021-09-10 23:36 UTC, franknoirot commented on cms/schemas/documents/social.js
> +import { FaHashtag } from 'react-icons/fa'
Please import the `preview` function from the iconPicker plugin. Look at the top of the `/documents/service.js` file for the import statement.

2021-09-10 23:36 UTC, franknoirot commented on cms/schemas/documents/social.js
> +        }
You do need a `prepare()` function in this case within `preview`, because the iconPicker plugin needs to run the icon through the `preview()` function that it exports. Check out the `documents/service.js` file for how its prepare function looks.

2021-09-10 23:36 UTC, franknoirot commented on cms/schemas/documents/term.js
> +                media: <span style={{fontSize: '0.75rem', background: PARTS_OF_SPEECH[type], padding: '.5em', borderRadius: '0.25rem'}}>{ type.slice(0,3) }.</span>
Nice 💅🏻

2021-09-10 23:37 UTC, franknoirot commented
Oh also I love the document type you added.

2021-09-13 13:59 UTC, netamorphosis-dev commented
Will review those items -- I tried to base my work on service and (glossary) term, but should've probably hit the docs first before struggling with the prepare method. Thanks @franknoirot!

2021-09-13 13:59 UTC, merged